[font]
size = 17.0

[font.normal]
family = "JetBrains Mono"

[window]
opacity = 0.9
dynamic_padding = true
decorations = "none"

[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]
